'use strict';

function json(value) { return JSON.stringify(value); }

const BUY_BALLS_SCRIPT = ({ ballId, quantity }) => String.raw`(async()=>{const ballId=${json(Number(ballId))},requested=${json(Number(quantity))};if(!Number.isInteger(ballId)||ballId<1||!Number.isInteger(requested)||requested<1)return{ok:false,operationStatus:'failed',reason:'invalid_purchase'};let bought=0,gold;const result=(extra={})=>{const operationStatus=bought>=requested?'completed':bought>0?'partial':'failed';return{...extra,ok:operationStatus==='completed',operationStatus,operationOk:operationStatus==='completed',retryAllowed:operationStatus==='failed'&&!extra.requiresTown,requested,bought,remaining:Math.max(0,requested-bought),gold}};for(let remaining=requested;remaining>0;){const qty=Math.min(1000,remaining);let response,data;try{response=await fetch('/api/game/shop/buy',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({ballId,qty})});data=await response.json().catch(()=>({}))}catch(error){return result({reason:bought?'purchase_partial':'purchase_failed',transportError:true})}const confirmed=Math.min(qty,Math.max(0,Number(data.bought)||0));bought+=confirmed;gold=Number.isFinite(Number(data.gold))?Number(data.gold):gold;if(response.status===401)return result({reason:'game_auth_required'});if(!response.ok)return result({requiresTown:Boolean(data.requiresTown)||/city|cidade|town/i.test(String(data.error||data.message||'')),reason:String(data.error||data.message||'purchase_failed')});if(confirmed===0)break;remaining=requested-bought}return result()})()`;

const SELL_ITEMS_SCRIPT = (items) => String.raw`(async()=>{const items=${json(items)};const requested=Array.isArray(items)?items.reduce((sum,item)=>sum+Math.max(0,Number(item&&item.qty)||0),0):0;if(!Array.isArray(items)||!items.length||requested<1)return{ok:false,operationStatus:'failed',reason:'invalid_sale'};let response,data;try{response=await fetch('/api/game/shop/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({items})});data=await response.json().catch(()=>({}))}catch(error){return{ok:false,operationStatus:'failed',operationOk:false,reason:'sale_failed',transportError:true,requestedCount:requested,soldCount:0}}const soldCount=Math.max(0,Number(data.soldCount)||0),serverRequested=Math.max(1,Number(data.requestedCount||data.requested)||requested),operationStatus=Boolean(data.partial)?'partial':soldCount>=serverRequested?'completed':soldCount>0?'partial':'failed';if(response.status===401)return{ok:false,operationStatus:'failed',operationOk:false,reason:'game_auth_required',requestedCount:serverRequested,soldCount};if(!response.ok)return{ok:false,operationStatus,operationOk:operationStatus==='completed',requiresTown:Boolean(data.requiresTown)||/city|cidade|town/i.test(String(data.error||data.message||'')),retryAllowed:operationStatus==='failed'&&!soldCount,reason:String(data.error||data.message||'sale_failed'),requestedCount:serverRequested,soldCount};return{ok:operationStatus==='completed',operationStatus,operationOk:operationStatus==='completed',retryAllowed:false,requestedCount:serverRequested,soldCount,goldGained:Math.max(0,Number(data.goldGained)||0) }})()`;

const SELL_POKEMON_SCRIPT = (pokeIds) => String.raw`(async()=>{const pokeIds=${json(pokeIds)},requested=Array.isArray(pokeIds)?pokeIds.length:0;if(!Array.isArray(pokeIds)||!pokeIds.length)return{ok:false,operationStatus:'failed',reason:'invalid_sale'};let response,data;try{response=await fetch('/api/game/pokemon/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({pokeIds})});data=await response.json().catch(()=>({}))}catch(error){return{ok:false,operationStatus:'failed',operationOk:false,reason:'sale_failed',transportError:true,requestedCount:requested,soldCount:0}}const soldCount=Math.min(requested,Math.max(0,Number(data.soldCount||data.sold)||0)),serverRequested=Math.max(1,Number(data.requestedCount||data.requested)||requested),operationStatus=Boolean(data.partial)?'partial':soldCount>=serverRequested?'completed':soldCount>0?'partial':'failed';if(response.status===401)return{ok:false,operationStatus:'failed',operationOk:false,reason:'game_auth_required',requestedCount:serverRequested,soldCount};if(!response.ok)return{ok:false,operationStatus,operationOk:operationStatus==='completed',requiresTown:Boolean(data.requiresTown)||/city|cidade|town/i.test(String(data.error||data.message||'')),retryAllowed:operationStatus==='failed'&&!soldCount,reason:String(data.error||data.message||'sale_failed'),requestedCount:serverRequested,soldCount};return{ok:operationStatus==='completed',operationStatus,operationOk:operationStatus==='completed',retryAllowed:false,requestedCount:serverRequested,soldCount,goldGained:Math.max(0,Number(data.goldGained)||0) }})()`;

const SELL_STONE_SCRIPT = ({ itemId, quantity }) => String.raw`(async()=>{const itemId=${json(Number(itemId))},requested=${json(Number(quantity))};if(!Number.isInteger(itemId)||itemId<1||!Number.isInteger(requested)||requested<1)return{ok:false,operationStatus:'failed',reason:'invalid_sale'};let response,data;try{response=await fetch('/api/game/flint/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({itemId,qty:requested})});data=await response.json().catch(()=>({}))}catch(error){return{ok:false,operationStatus:'failed',operationOk:false,reason:'sale_failed',transportError:true,requestedCount:requested,sold:0}}const sold=Math.min(requested,Math.max(0,Number(data.sold)||0)),serverRequested=Math.max(1,Number(data.requestedCount||data.requested)||requested),operationStatus=Boolean(data.partial)?'partial':sold>=serverRequested?'completed':sold>0?'partial':'failed';if(response.status===401)return{ok:false,operationStatus:'failed',operationOk:false,reason:'game_auth_required',requestedCount:serverRequested,sold};if(!response.ok)return{ok:false,operationStatus,operationOk:operationStatus==='completed',requiresTown:Boolean(data.requiresTown)||/city|cidade|town/i.test(String(data.error||data.message||'')),retryAllowed:operationStatus==='failed'&&!sold,reason:String(data.error||data.message||'sale_failed'),requestedCount:serverRequested,sold};return{ok:operationStatus==='completed',operationStatus,operationOk:operationStatus==='completed',retryAllowed:false,requestedCount:serverRequested,sold,goldGained:Math.max(0,Number(data.goldGained)||0) }})()`;

module.exports = { BUY_BALLS_SCRIPT, SELL_ITEMS_SCRIPT, SELL_POKEMON_SCRIPT, SELL_STONE_SCRIPT };
