'use strict';

function json(value) { return JSON.stringify(value); }

const BUY_BALLS_SCRIPT = ({ ballId, quantity }) => String.raw`(async()=>{const ballId=${json(Number(ballId))},requested=${json(Number(quantity))};if(!Number.isInteger(ballId)||ballId<1||!Number.isInteger(requested)||requested<1)return{ok:false,reason:'invalid_purchase'};let bought=0,gold;for(let remaining=requested;remaining>0;){const qty=Math.min(1000,remaining);const response=await fetch('/api/game/shop/buy',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({ballId,qty})});const data=await response.json().catch(()=>({}));if(response.status===401)return{ok:false,reason:'game_auth_required',requested,bought,remaining:requested-bought};if(!response.ok)return{ok:false,reason:String(data.error||data.message||'purchase_failed'),requested,bought,remaining:requested-bought};const confirmed=Math.max(0,Number(data.bought)||0);bought+=confirmed;gold=Number.isFinite(Number(data.gold))?Number(data.gold):gold;if(confirmed===0)break;remaining=requested-bought}return{ok:bought>0,requested,bought,remaining:Math.max(0,requested-bought),gold}})()`;

const SELL_ITEMS_SCRIPT = (items) => String.raw`(async()=>{const items=${json(items)};if(!Array.isArray(items)||!items.length)return{ok:false,reason:'invalid_sale'};const response=await fetch('/api/game/shop/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({items})});const data=await response.json().catch(()=>({}));if(response.status===401)return{ok:false,reason:'game_auth_required'};if(!response.ok)return{ok:false,reason:String(data.error||data.message||'sale_failed')};return{ok:true,soldCount:Math.max(0,Number(data.soldCount)||0),goldGained:Math.max(0,Number(data.goldGained)||0)}})()`;

const SELL_POKEMON_SCRIPT = (pokeIds) => String.raw`(async()=>{const pokeIds=${json(pokeIds)};if(!Array.isArray(pokeIds)||!pokeIds.length)return{ok:false,reason:'invalid_sale'};const response=await fetch('/api/game/pokemon/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({pokeIds})});const data=await response.json().catch(()=>({}));if(response.status===401)return{ok:false,reason:'game_auth_required'};if(!response.ok)return{ok:false,reason:String(data.error||data.message||'sale_failed')};return{ok:true,soldCount:Math.max(0,Number(data.soldCount||data.sold)||0),goldGained:Math.max(0,Number(data.goldGained)||0)}})()`;

const SELL_STONE_SCRIPT = ({ itemId, quantity }) => String.raw`(async()=>{const itemId=${json(Number(itemId))},qty=${json(Number(quantity))};if(!Number.isInteger(itemId)||itemId<1||!Number.isInteger(qty)||qty<1)return{ok:false,reason:'invalid_sale'};const response=await fetch('/api/game/flint/sell',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({itemId,qty})});const data=await response.json().catch(()=>({}));if(response.status===401)return{ok:false,reason:'game_auth_required'};if(!response.ok)return{ok:false,reason:String(data.error||data.message||'sale_failed')};return{ok:true,sold:Math.max(0,Number(data.sold)||0),goldGained:Math.max(0,Number(data.goldGained)||0)}})()`;

module.exports = { BUY_BALLS_SCRIPT, SELL_ITEMS_SCRIPT, SELL_POKEMON_SCRIPT, SELL_STONE_SCRIPT };
