'use strict';

const BOOTSTRAP_SCRIPT = String.raw`(()=>{if(window.__darkGrid)return{ok:true,existing:true};const P={version:1,ws:{},api:{},outbound:[],lastEventAt:Date.now(),lastSlug:'',travelTemplate:null,session:{start:Date.now(),kills:0,xp:0,captures:0,balls:0,shiny:0,drops:{}}};const remember=(type,data)=>{P.lastEventAt=Date.now();P.ws[type]=data;const s=P.session;if(type==='field-init'){const slug=String(data&&data.slug||'');if(slug&&slug!==P.lastSlug){P.lastSlug=slug;s.start=Date.now();s.kills=0;s.xp=0;s.captures=0;s.balls=0;s.shiny=0;s.drops={};const candidate=[...P.outbound].reverse().find(x=>x&&x.json&&JSON.stringify(x.json).includes(slug)&&x.json.type!=='inv-get');if(candidate)P.travelTemplate={oldSlug:slug,json:candidate.json};}}else if(type==='field-kill'){s.kills++;s.xp+=Number(data&&data.xpGained)||0;(data&&data.loot||[]).forEach(x=>{const id=String(x&&x.itemId||'unknown');const d=s.drops[id]||(s.drops[id]={name:String(x&&x.name||id),qty:0});d.qty+=Number(x&&x.qty)||0;});if(data&&data.shiny)s.shiny++;}else if(type==='catch-result'){s.balls++;if(data&&data.success)s.captures++;}};const OW=window.WebSocket;function DGSocket(...args){const socket=Reflect.construct(OW,args,new.target||DGSocket);P.socket=socket;const send=socket.send.bind(socket);socket.send=(value)=>{try{const json=typeof value==='string'?JSON.parse(value):null;if(json){P.outbound.push({json,t:Date.now()});if(P.outbound.length>40)P.outbound.shift();}}catch{}return send(value)};socket.addEventListener('message',event=>{try{const data=JSON.parse(event.data);if(data&&data.type)remember(String(data.type),data)}catch{}});return socket;}DGSocket.prototype=OW.prototype;Object.keys(OW).forEach(k=>{try{DGSocket[k]=OW[k]}catch{}});window.WebSocket=DGSocket;const OF=window.fetch;window.fetch=function(...args){const result=OF.apply(this,args);try{const url=String((args[0]&&args[0].url)||args[0]||'');if(/\/api\/characters\/me|\/game\/items\.json|\/api\/game\/map-markers/.test(url))result.then(r=>r.clone().json().then(data=>{P.api[url.split('?')[0]]=data}).catch(()=>{})).catch(()=>{})}catch{}return result};window.__darkGrid=P;return{ok:true,version:P.version}})()`;

const READ_STATE_SCRIPT = String.raw`(()=>{const P=window.__darkGrid;if(!P)return{ok:false,reason:'collector_missing'};const ch=((P.api['/api/characters/me']||{}).character)||{};const ws=P.ws||{},inv=((ws.inventory||{}).items)||[],balls=ws.balls&&ws.balls.counts?Object.values(ws.balls.counts).reduce((a,b)=>a+(Number(b)||0),0):0;const seconds=Math.max(1,(Date.now()-(P.session.start||Date.now()))/1000);const drops=Object.values(P.session.drops||{});const status=ch.id?(Date.now()-P.lastEventAt<90000?'online':'stale'):'login_required';return{ok:true,collectorVersion:P.version,characterId:ch.id||'',name:ch.name||'',level:Number(ch.level)||0,gold:Number(ch.gold)||0,huntSlug:String(P.lastSlug||''),status,balls,potions:inv.reduce((sum,x)=>sum+(Number(x.quantity)||0),0),metrics:{kills:P.session.kills||0,xp:P.session.xp||0,captures:P.session.captures||0,shiny:P.session.shiny||0,seconds:Math.round(seconds),xph:Math.round((P.session.xp||0)/seconds*3600),kph:Math.round((P.session.kills||0)/seconds*3600)},drops}})()`;

const OPEN_MARKET_SCRIPT = String.raw`(async()=>{const wait=n=>new Promise(r=>setTimeout(r,n));const open=()=>!!document.querySelector('[class*="mkt2-"],.mk-window');if(open())return{ok:true};const direct=[...document.querySelectorAll('[data-guide*="market" i],button.npc-plate-btn,button')].find(x=>!x.disabled&&x.getClientRects().length&&/market|mercado/i.test(String(x.textContent||'')+' '+String(x.getAttribute('data-guide')||'')));if(direct){direct.click();for(let n=0;n<20;n++){await wait(100);if(open())return{ok:true}}}const root=document.querySelector('.game-root'),key=root&&Object.keys(root).find(k=>k.startsWith('__reactFiber$'));if(!key)return{ok:false,reason:'market_control_missing'};let fiber=root[key];while(fiber){const hooks=[];let h=fiber.memoizedState;while(h&&hooks.length<300){hooks.push(h);h=h.next}for(let p=1;p<hooks.length;p++){if(hooks[p].memoizedState!=='Mercado')continue;for(let d=0;d<24;d++){for(const off of [9-d,9+d]){const candidate=hooks[p-off];if(candidate&&candidate.memoizedState===false&&candidate.queue&&typeof candidate.queue.dispatch==='function'){candidate.queue.dispatch(true);await wait(100);if(open())return{ok:true};candidate.queue.dispatch(false)}}}}fiber=fiber.return}return{ok:false,reason:'market_control_missing'}})()`;

const OPEN_DEPOT_SCRIPT = String.raw`(async()=>{
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const visible=element=>{if(!element)return false;const style=getComputedStyle(element),box=element.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&box.width>0&&box.height>0};
const open=()=>[...document.querySelectorAll('.dpt-window,.dep-window,.depot-window,[class*="dpt-window"],[class*="dep-window"],[class*="depot-window"]')].some(visible);
if(open())return{ok:true};
const dialog=[...document.querySelectorAll('.npc-dialog')].find(element=>visible(element)&&/depot|depósito|deposito/i.test(element.innerText||''));
const direct=dialog&&[...dialog.querySelectorAll('button,[role="button"],a')].find(element=>visible(element)&&/abrir|open|depot|depósito|deposito/i.test(element.textContent||''));
const marker=direct||document.querySelector('#dock-btn-depot,[data-guide="dock-depot"],[data-guide*="depot" i],[data-guide*="storage" i]');
if(marker){marker.click();for(let attempt=0;attempt<25;attempt+=1){await wait(100);if(open())return{ok:true}}}
const root=document.querySelector('.game-root'),fiberKey=root&&Object.keys(root).find(key=>key.startsWith('__reactFiber$'));
if(fiberKey){let fiber=root[fiberKey];while(fiber){const hooks=[];let hook=fiber.memoizedState;while(hook&&hooks.length<300){hooks.push(hook);hook=hook.next}for(let position=1;position<hooks.length;position+=1){if(hooks[position].memoizedState!=='Mercado')continue;for(let distance=0;distance<24;distance+=1){for(const offset of [9-distance,9+distance]){const candidate=hooks[position-offset];if(!candidate||candidate.memoizedState!==false||!candidate.queue||typeof candidate.queue.dispatch!=='function')continue;candidate.queue.dispatch(true);await wait(110);if(open())return{ok:true};candidate.queue.dispatch(false)}}}fiber=fiber.return}}
return{ok:false,reason:'depot_control_missing'};
})()`;

const TRAVEL_SCRIPT = (slug,name) => String.raw`(async()=>{const P=window.__darkGrid,slug=${JSON.stringify(String(slug||''))},name=${JSON.stringify(String(name||''))};const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();const replace=(v,old,next)=>{if(typeof v==='string')return v===old?next:v.replace(old,next);if(Array.isArray(v))return v.map(x=>replace(x,old,next));if(v&&typeof v==='object'){const out={};Object.keys(v).forEach(k=>out[k]=replace(v[k],old,next));return out}return v};if(P&&P.socket&&P.socket.readyState===1&&P.travelTemplate&&P.travelTemplate.json){try{P.socket.send(JSON.stringify(replace(P.travelTemplate.json,P.travelTemplate.oldSlug,slug)));return{ok:true,mode:'socket'}}catch{}}const target=norm(name||slug);const button=[...document.querySelectorAll('.map-window button.hunt-marker,[data-guide^="hunt-"]')].find(x=>norm(x.textContent||x.title||'').includes(target)||norm(x.dataset&&x.dataset.guide).includes(target));if(button&&!button.disabled){button.click();return{ok:true,mode:'map'}}return{ok:false,reason:'hunt_not_found'}})()`;

module.exports = { BOOTSTRAP_SCRIPT, READ_STATE_SCRIPT, OPEN_MARKET_SCRIPT, OPEN_DEPOT_SCRIPT, TRAVEL_SCRIPT };
