'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'renderer', 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, '..', 'src', 'renderer', 'app.js'), 'utf8');
assert.match(html, /id="logoutButton"/);
assert.match(html, /id="operationsModal"/);
assert.match(html, /id="buyBallsForm"/);
assert.match(html, /id="performanceValue"/);
assert.match(html, /id="historyList"/);
assert.match(html, /id="alertSettingsForm"/);
assert.match(html, /id="alertNativeNotifications"/);
assert.match(html, /id="exportHistoryButton"/);
assert.match(html, /id="inventoryModal"/);
assert.match(html, /id="loadDepotButton"/);
assert.match(html, /id="teamModal"/);
assert.match(html, /id="sellPokemonButton"/);
assert.match(html, /id="huntModal"/);
assert.match(html, /id="huntOptions"/);
assert.match(html, /id="rememberGameCredentials"/);
assert.match(html, /id="compactButton"/);
assert.match(html, /id="layoutButton"/);
assert.match(html, /id="tierlistModal"/);
assert.match(app, /authLogout\(\)/);
assert.match(app, /removeAccount\(account\.id\)/);
assert.match(app, /Remover .* do DarkGrid/);
assert.match(app, /accountAction\(account\.id, action/);
assert.match(app, /loadHuntHistory\(\)/);
assert.match(app, /saveAlertConfig/);
assert.match(app, /exportHuntHistory/);
assert.match(app, /openInventory/);
assert.match(app, /readDepot/);
assert.match(app, /openTeam/);
assert.match(app, /previewSellPokemon/);
assert.match(app, /travelToHunt/);
assert.match(app, /readHunts/);
assert.match(app, /calculateTierlist/);
assert.match(app, /setAccountsVisible/);
assert.match(app, /setCompactMode/);
assert.match(app, /setLayoutMode/);
console.log('DarkGrid renderer: logout encerra painéis sem apagar perfis locais');
